# Generated by Django 4.2.1 on 2023-06-04 08:54

import borrow.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ("book", "0003_alter_booksmodel_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowBy", models.CharField(default="", max_length=20)),
                (
                    "borrowDate",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 4, 8, 54, 47, 462836)
                    ),
                ),
                (
                    "returnException",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 4, 8, 54, 47, 462850)
                    ),
                ),
                ("isApproved", models.BooleanField(default=False)),
                (
                    "bookID",
                    models.ManyToManyField(
                        to="book.booksmodel",
                        validators=[borrow.models.validate_max_picks],
                    ),
                ),
            ],
        ),
    ]
