# Generated by Django 4.2.1 on 2023-06-04 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BooksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=255)),
                ("bookTitle", models.CharField(max_length=50)),
                ("bookCategory", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=255)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 4, 8, 46, 17, 411270)
                    ),
                ),
                ("isAvailable", models.BooleanField(default=False)),
            ],
        ),
    ]
