# Generated by Django 4.2.1 on 2023-06-04 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_booksmodel_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksmodel",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 4, 8, 54, 47, 462132)
            ),
        ),
    ]
