# Generated by Django 4.2.1 on 2023-06-04 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrow", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "returnDate",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 4, 8, 51, 26, 385956)
                    ),
                ),
                ("isApproved", models.BooleanField(default=False)),
                (
                    "borrowID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="borrow.borrow"
                    ),
                ),
            ],
        ),
    ]
